@startuml
'https://plantuml.com/class-diagram


class Project{
- events : List<Event>
+ Project()
+ calculateDuration()
+ getDuration() : Duration
+ addEvent(e : Event)
+ endProject()
+ setProj_name(proj_name : String[])
- delete(e : Event)
}

class Task{
- task_intervals : ArrayList<Interval>
+ Task()
+ addEvent(event : Event)
+ setTaskName(name : String[])
+ getDuration() : Duration
+ startTask()
+ getTask_intervals() : ArrayList<interval>
+ calculateDuration()
+ acceptVisitor(visitor : Visitor)
}

abstract Event{
# name : String[]
# initTime : LocalDateTime
# endTime : LocalDateTime
# event_duration : Duration
- father : Event
+ Event()
+ setName(n : String[])
+ getName() : String[]
+ //addEvent(event : Event)//
+ getInitTime() : LocalDateTime
+ getEndTime() : LocalDateTime
+ setInitTime()
+ setEndTime()
+ setDuration()
+ getFather() : Event
+ getDuration() : Duration
+ //calculateDuration()//
+ //acceptVisitor(visitor : Visitor)//
}

class Clock{
- timer : Timer
- dateTime : LocalDateTime
- instance : Clock
- Clock()
+ //getInstance() : Clock//
+ getDateTime() : LocalDateTime
+ stop()
- //tick()//
+ //notifyObservers()//
}

class Interval{
- initTime : LocalDateTime
- endTime : DateTime
- duration : Duration /'cada golpe de reloj incremento'/
- task : Task
+ Interval(t : Task)
+ getTask() : Task
+ update()
+ getInitTime() : LocalDateTime
+ getEndTime() : LocalDateTime
+ getDuration() : Duration
+ endInterval()
+ acceptVisitor(visitor : Visitor)
}

interface Visitor{
+ visitTask(t : Task)
+ visitProject(p : Project)
+ visitInterval(i : Interval)
}

class Print{
- root : Event
- //instance : Print//
+ Print()
+ //getInstance() : Print//
+ printerInterval()
+ visitTask(t : Task)
+ visitInterval(i : Interval)
+ visitProject(p : Project)
}

package "java.utils"{
interface Observer{
+ update(arg0 : Observable, arg1 : Object)
}

abstract Observable{
+ addObserver(ob : Observer)
+ deleteObserver(ob : Observer)
+ setChanged()
+ notifyObservers(arg0 : Observable, arg1: Object}
}
}

class Client{
void main()
}

Event <|-- Task
Event <|-- Project

Event "1" <--* "0..*" Project
Observable <|-- Clock
Observer <|-- Interval
Observer "1" <--o "0..*" Observable
Interval "0..*" --*  "1" Task
Event <-- Client
Visitor <-- Client
Print --|> Visitor



@enduml